# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

ClassicVote:
  fields:
    default: user, candidate
    form: user, candidate
  order_by: 
  relationships: candidate, user
  filters: created_at
  search: 
  application: vote-de-valeur

