# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Candidate:
  fields:
    default: name, favorite
    form: name, favorite
  action:
    index: test
    edit: test
  order_by: 
  relationships: 
  filters: created_at
  search: name
  application: vote-de-valeur

Vote:
  fields:
    default: candidate, vote, key
    form: candidate, vote, key
  order_by: 
  relationships: candidate
  search: 
  application: vote-de-valeur

