# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

ClassicVote:
  fields:
    default: candidate
    form: candidate
  order_by: 
  relationships: candidate
  filters: created_at
  search: 
  application: vote-de-valeur

