# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Candidate:
  fields:
    default: name
    form: name
  order_by: 
  relationships: 
  filters: created_at
  search: name
  application: vote-de-valeur

User:
  fields:
    default: id, email, first_name, last_name, postal_code, public, a_vote, a_vote_classic, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip, confirmation_token, confirmed_at, confirmation_sent_at, failed_attempts, unlock_token, locked_at
    form: email, first_name, last_name, postal_code, public, a_vote, a_vote_classic, reset_password_token, reset_password_sent_at, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip, confirmation_token, confirmed_at, confirmation_sent_at, failed_attempts, unlock_token, locked_at
  order_by:
  relationships: votes, classic_vote
  filters: created_at
  search: 
  application: vote-de-valeur
  options:
    export: csv, json, xml

Vote:
  fields:
    default: candidate, vote
    form: candidate, vote
  order_by: 
  relationships: candidate
  filters: created_at
  search: 
  application: vote-de-valeur

