# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Candidate:
  fields:
    default: name
    form: name
  order_by: 
  relationships: 
  filters: created_at
  search: name
  application: vote-de-valeur

Vote:
  fields:
    default: candidate, vote
    form: candidate, vote
  order_by: 
  relationships: candidate
  filters: created_at
  search: 
  application: vote-de-valeur

