#
# Format:
# 
# <heroku_san shorthand name>:
#   app: <Heroku app name>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production: 
  app: not_an_app
  config:
    BUNDLE_WITHOUT: "development:test"
    GOOGLE_ANALYTICS: "UA-12345678-1"

staging:
  app: evening-moon-670
  config:
    BUNDLE_WITHOUT: "development:test"
    GOOGLE_ANALYTICS: "UA-23743742-1"

demo: 
  app: awesomeapp-demo
  config: *default
